version: '3.4'

services:
  postgres95:
    image: postgres:9.5
    restart: always
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "55413:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql56:
    image: mysql:5.6
    restart: always
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - "33309:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MSSQLServer-Passw0rd
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "18000:8000"
  mongo:
    image: weshigbee/docker-mongo-sample-datasets@sha256:db0324e7b3a49096d10f4062bedc6120a258bfb0483fffb8de8a687d419d15dc
    restart: always
    ports:
      - "27017:27017"
